# Generated by Django 3.2.6 on 2022-01-23 21:16

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta_cod', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje_descuento', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de descuento')),
                ('chk_delete', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ingresado', models.DateTimeField(null=True, verbose_name='Fecha de registro')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('ingresado', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Productos',
                'db_table': 'tipoproducto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=150, verbose_name='Marca')),
                ('precio_costo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Costo')),
                ('precio_venta', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Venta')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock')),
                ('es_oferta', models.CharField(default='N', max_length=1, verbose_name='Oferta')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('chk_oferta', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ingresado', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor', verbose_name='Proveedor')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.tipoproducto', verbose_name='Tipo Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_descuento', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de descuento')),
                ('fecha_inicio_oferta', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin_oferta', models.DateField(verbose_name='Fecha de fin')),
                ('ingresado', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('producto_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.producto', verbose_name='Producto a ofertar')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'db_table': 'oferta',
                'ordering': ['id'],
            },
        ),
    ]
