# Generated by Django 4.0.3 on 2022-05-19 00:55

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock actual')),
                ('es_procesado', models.CharField(default='N', max_length=1, verbose_name='procesado')),
                ('fecha_registro', models.DateField(default=datetime.datetime.now)),
                ('autorizado_por', models.CharField(blank=True, max_length=20, null=True, verbose_name='autorizado_por')),
                ('cant', models.IntegerField(default=0)),
                ('archivo', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Oferta_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta_cod', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje_descuento', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de descuento')),
                ('chk_delete', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ingresado', models.DateTimeField(null=True, verbose_name='Fecha de registro')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('ingresado', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Productos',
                'db_table': 'tipoproducto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=150, verbose_name='Marca')),
                ('precio_costo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Costo')),
                ('precio_venta', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Venta')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock')),
                ('es_oferta', models.CharField(default='N', max_length=1, verbose_name='Oferta')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('chk_oferta', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ingresado', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor', verbose_name='Proveedor')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.tipoproducto', verbose_name='Tipo Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_descuento', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de descuento')),
                ('fecha_inicio_oferta', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin_oferta', models.DateField(verbose_name='Fecha de fin')),
                ('ingresado', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('producto_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.producto', verbose_name='Producto a ofertar')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'db_table': 'oferta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=150, null=True, verbose_name='motivo')),
                ('cantprod', models.IntegerField(default=0)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.inventario')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Inventario',
                'verbose_name_plural': 'Detalles de Inventario',
                'ordering': ['id'],
            },
        ),
    ]
