# Generated by Django 4.0.3 on 2022-05-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_alter_inventario_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='archivo',
        ),
    ]
