# Generated by Django 4.0.3 on 2022-05-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0004_filesuploads_remove_inventario_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='file_ad',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
