# Generated by Django 4.0.3 on 2022-05-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_inventario_file_ad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='file_ad',
        ),
    ]
