# Generated by Django 4.0.3 on 2022-05-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0006_remove_inventario_file_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
