# Generated by Django 4.0.3 on 2022-05-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0009_remove_inventario_file_inventario_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='image',
        ),
    ]
