# Generated by Django 4.0.3 on 2022-05-19 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Embresa')),
                ('timbrado', models.IntegerField(unique=True, verbose_name='Timbrado')),
                ('ruc', models.CharField(max_length=150, unique=True, verbose_name='Ruc')),
                ('fecha_vencimiento', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de validez')),
                ('direccion', models.CharField(max_length=300, verbose_name='Direccion')),
                ('telefono', models.CharField(default='', max_length=300, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=400, verbose_name='E-Mail')),
                ('ingresado', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['id'],
            },
        ),
    ]
