# Generated by Django 4.0.3 on 2022-05-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0002_empresa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='establecimiento',
            field=models.CharField(default='001', max_length=3, verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='punto_expedicion',
            field=models.CharField(default='001', max_length=3, verbose_name='Punto de expedicion'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Empresa'),
        ),
    ]
