# Generated by Django 4.0.3 on 2022-05-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0003_empresa_establecimiento_empresa_punto_expedicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(max_length=150, verbose_name='Ruc'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='timbrado',
            field=models.IntegerField(verbose_name='Timbrado'),
        ),
    ]
