# Generated by Django 4.0.3 on 2022-05-19 00:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetNotaCreditoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantnota', models.IntegerField(default=0)),
                ('totalnota', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('desc', models.CharField(blank=True, max_length=150, null=True, verbose_name='desc')),
            ],
            options={
                'verbose_name': 'Detalle de Nota Credito Venta',
                'verbose_name_plural': 'Detalles de Nota Credito Venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NotaCreditoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_nota', models.CharField(blank=True, max_length=150, null=True, verbose_name='desc')),
                ('fecha_emision_nota', models.DateField(default=datetime.datetime.now)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('nro_factura', models.IntegerField(default=0)),
                ('cant', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Nota Credito Venta',
                'verbose_name_plural': 'Notas Credito Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.FloatField(default=0.0)),
                ('es_procesado', models.CharField(default='N', max_length=1, verbose_name='procesado')),
                ('pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta Debito', 'Tarjeta Debito'), ('Tarjeta Credito', 'Tarjeta Credito'), ('Giro Movil', 'Giro Movil')], default='efectivo', max_length=40)),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
    ]
