# Generated by Django 4.0.3 on 2022-04-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0002_sale_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='es_procesado',
            field=models.CharField(default='N', max_length=1, verbose_name='procesado'),
        ),
    ]
