# Generated by Django 4.0.3 on 2022-05-19 00:55

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proveedor', '0001_initial'),
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock actual')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('pago', models.CharField(choices=[('Contado', 'Contado'), ('Credito', 'Credito')], default='Contado', max_length=40)),
                ('fecha_compra', models.DateField(default=datetime.datetime.now)),
                ('fecha_vencimiento', models.DateField(default=datetime.datetime.now)),
                ('cant_cuota', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')], default=0)),
                ('desc', models.CharField(blank=True, max_length=150, null=True, verbose_name='desc')),
                ('es_procesado', models.CharField(default='N', max_length=1, verbose_name='procesado')),
                ('fecha_emision_nota', models.DateField(default=datetime.datetime.now)),
                ('prov_datos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('desc', models.CharField(blank=True, max_length=150, null=True, verbose_name='desc')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compra.compra')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalle de Compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NotaCreditoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_nota', models.CharField(blank=True, max_length=150, null=True, verbose_name='desc')),
                ('fecha_emision_nota', models.DateField(default=datetime.datetime.now)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('nro_factura', models.IntegerField(default=0)),
                ('cant', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Nota Credito Proveedor',
                'verbose_name_plural': 'Notas Credito Proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetNotaCreditoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantnota', models.IntegerField(default=0)),
                ('totalnota', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('desc', models.CharField(blank=True, max_length=150, null=True, verbose_name='desc')),
                ('detcompra_datos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compra.detcompra')),
                ('notacredito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compra.notacreditocompra')),
            ],
            options={
                'verbose_name': 'Detalle de Nota Credito Compra',
                'verbose_name_plural': 'Detalles de Nota Credito Compra',
                'ordering': ['id'],
            },
        ),
    ]
