# Generated by Django 4.0.4 on 2022-04-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='es_procesado',
            field=models.CharField(default='N', max_length=1, verbose_name='procesado'),
        ),
    ]
