# Generated by Django 4.0.3 on 2022-04-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0002_compra_cant_cuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cant_cuota',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], default=0),
        ),
    ]
