# Generated by Django 4.0.3 on 2022-04-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0003_alter_compra_cant_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='desc_nota',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='desc'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='cant_cuota',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')], default=0),
        ),
    ]
