# Generated by Django 4.0.3 on 2022-04-08 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0004_compra_desc_nota_alter_compra_cant_cuota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='desc_nota',
        ),
        migrations.CreateModel(
            name='NotaCreditoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_nota', models.CharField(blank=True, max_length=150, null=True, verbose_name='desc')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compra.compra')),
                ('detcompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compra.detcompra')),
            ],
            options={
                'verbose_name': 'Nota Credito Proveedor',
                'verbose_name_plural': 'Notas Credito Proveedores',
                'ordering': ['id'],
            },
        ),
    ]
