# Generated by Django 4.0.3 on 2022-04-08 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0005_remove_compra_desc_nota_notacreditocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacreditocompra',
            name='fecha_emision',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='notacreditocompra',
            name='razon',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='razon'),
        ),
    ]
