# Generated by Django 4.0.3 on 2022-04-12 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0007_compra_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_emision_nota',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
