# Generated by Django 4.0.3 on 2022-04-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0008_compra_fecha_emision_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notacreditocompra',
            old_name='compra',
            new_name='compra_datos',
        ),
        migrations.RenameField(
            model_name='notacreditocompra',
            old_name='desc_nota',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='notacreditocompra',
            old_name='detcompra',
            new_name='detcompra_datos',
        ),
        migrations.RenameField(
            model_name='notacreditocompra',
            old_name='fecha_emision',
            new_name='fecha_emision_nota',
        ),
    ]
