# Generated by Django 4.0.3 on 2022-04-16 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0009_rename_compra_notacreditocompra_compra_datos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notacreditocompra',
            name='compra_datos',
        ),
    ]
