# Generated by Django 4.0.3 on 2022-04-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0010_remove_notacreditocompra_compra_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='detcompra',
            name='nro_factura',
            field=models.IntegerField(default=0),
        ),
    ]
