# Generated by Django 4.0.3 on 2022-04-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0011_detcompra_nro_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detcompra',
            name='nro_factura',
        ),
        migrations.AddField(
            model_name='notacreditocompra',
            name='cant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notacreditocompra',
            name='nro_factura',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notacreditocompra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
