# Generated by Django 4.0.3 on 2022-04-17 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0012_remove_detcompra_nro_factura_notacreditocompra_cant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notacreditocompra',
            old_name='desc',
            new_name='desc_nota',
        ),
    ]
