# Generated by Django 4.0.3 on 2022-04-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compra', '0013_rename_desc_notacreditocompra_desc_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notacreditocompra',
            name='razon',
        ),
    ]
