# Generated by Django 3.2.6 on 2022-01-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('cedula', models.IntegerField(unique=True, verbose_name='cedula')),
                ('direccion', models.CharField(max_length=150, verbose_name='dirección')),
                ('telefono', models.CharField(max_length=150, unique=True, verbose_name='teléfono')),
                ('desc', models.CharField(blank=True, max_length=150, null=True, verbose_name='desc')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 't_vendedor',
                'ordering': ['id'],
            },
        ),
    ]
