# Generated by Django 3.2.6 on 2022-01-23 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('ci', models.IntegerField(unique=True, verbose_name='Cedula')),
                ('genero', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10, verbose_name='Sexo')),
                ('ruc', models.CharField(max_length=150, unique=True, verbose_name='Ruc')),
                ('nacimiento', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(max_length=300, verbose_name='Direccion')),
                ('telefono', models.CharField(default='', max_length=300, verbose_name='Telefono')),
                ('ingresado', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['id'],
            },
        ),
    ]
