# Generated by Django 4.0.3 on 2022-05-30 23:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de inicio')),
                ('fecha_cierre', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Fecha de cierre')),
                ('monto_inicial', models.IntegerField(verbose_name='Monto inicial')),
                ('monto_final', models.IntegerField(null=True, verbose_name='Monto final')),
                ('total_venta', models.IntegerField(null=True, verbose_name='Total de ventas')),
                ('status', models.CharField(choices=[('1', 'abierto'), ('2', 'cerrado')], default='1', max_length=10, verbose_name='status')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'Caja',
                'ordering': ['id'],
            },
        ),
    ]
