# Generated by Django 4.0.3 on 2022-05-19 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('ruc', models.CharField(max_length=150, unique=True, verbose_name='Ruc')),
                ('direccion', models.CharField(max_length=300, verbose_name='Direccion')),
                ('correo', models.CharField(max_length=400, verbose_name='E-Mail')),
                ('telefono', models.CharField(default='', max_length=300, verbose_name='Telefono')),
                ('ingresado', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['id'],
            },
        ),
    ]
